# Generated by Django 3.2 on 2021-11-18 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerModel',
            fields=[
                ('identifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3)),
                ('home_address', models.CharField(max_length=255)),
                ('telecom', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
