# Generated by Django 3.2 on 2021-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitionermodel',
            name='practitioner_role',
            field=models.CharField(choices=[('doctor', 'Bác sĩ'), ('surgeon', 'Bác sĩ phẫu thuật'), ('medical assistant', 'Trợ lý y tế'), ('medical laboratory technician', 'Kỹ thuật viên phòng thí nghiệm y tế'), ('diagnostic imaging technician', 'Kỹ thuật viên chẩn đoán hình ảnh'), ('nurse', 'Y tá')], default='doctor', max_length=100),
        ),
    ]
