# Generated by Django 3.2 on 2021-11-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionermodel',
            name='practitioner_role',
            field=models.CharField(choices=[('doctor', 'Bác sĩ'), ('surgeon', 'Bác sĩ phẫu thuật'), ('medical assistant', 'Trợ lý y tế'), ('medical laboratory technician', 'Kỹ thuật viên phòng thí nghiệm y tế'), ('X-ray technician', 'Kỹ thuật viên X-quang'), ('ultrasound technician', 'Kỹ thuật viên siêu âm'), ('nurse', 'Y tá')], default='doctor', max_length=100),
        ),
    ]
