stages:
  - publish
  - deploy

variables:
  APP_NAME: dclv
  ANSIBLE_HOST_KEY_CHECKING: "False"

.dockerize:
  stage: publish
  script:
    - export APP_VER=${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - export IMAGE_TAG=namnguyen2307/${APP_NAME}:${APP_VER}
    - docker login -u namnguyen2307 -p abcxyz123
    - docker build -t ${IMAGE_TAG} -f Dockerfile .
    - docker push ${IMAGE_TAG}
    - docker rmi -f ${IMAGE_TAG}
  tags:
    - "dclv"

dockerize:binhthanh:
  extends:
    - .dockerize
  only:
    refs:
      - benhvienbinhthanh

dockerize:thuduc:
  extends:
    - .dockerize
  only:
    refs:
      - benhvienthuduc

.deploy:
  stage: deploy
  tags:
    - "ansible"

deploy:binhthanh:
  extends:
    - .deploy
  script:
    - export HAPI_HOST="http://10.20.20.145:8080/fhir"
    - export APP_VER=${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - export IMAGE_TAG=namnguyen2307/${APP_NAME}:${APP_VER}
    - ansible-galaxy collection install community.docker
    - ansible-playbook /etc/ansible/playbook/deploy.yml -e "host=binhthanh" -e "IMAGE_TAG=${IMAGE_TAG}"
  only:
    refs:
      - benhvienbinhthanh

deploy:thuduc:
  extends:
    - .deploy
  script:
    - export FHIR_SERVER="http://FHIR_SERVER:8080/fhir"
    - export APP_VER=${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    - export IMAGE_TAG=namnguyen2307/${APP_NAME}:${APP_VER}
    - ansible-galaxy collection install community.docker
    - ansible-playbook /etc/ansible/playbook/deploy.yml -e "FHIR_SERVER=http://35.219.75.55:8080/fhir" "host=thuduc" -e "IMAGE_TAG=${IMAGE_TAG}"
  only:
    refs:
      - benhvienthuduc
