version: "3"
services:
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:4.4.3
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=nam
      - MONGODB_PASSWORD=nam123
      - MONGODB_DATABASE=data
      - MONGODB_PORT_NUMBER=27018
    volumes:
      - ./data:/bitnami/mongodb/
    network_mode: host
    restart: always
  # Django:
  #   depends_on: mongodb 
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   network_mode: host
