# Generated by Django 3.2 on 2021-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('Nam', 'nam'), ('Nu', 'nu')], default='', max_length=3),
        ),
    ]
