# Generated by Django 3.2 on 2021-07-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='user_identifier',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='health_exam_status',
        ),
    ]
