# Generated by Django 3.2 on 2021-11-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('patient', 'Bệnh nhân'), ('doctor', 'Bác sĩ'), ('surgeon', 'Bác sĩ phẫu thuật'), ('medical assistant', 'Trợ lý y tế'), ('medical laboratory technician', 'Kỹ thuật viên phòng thí nghiệm y tế'), ('X-ray technician', 'Kỹ thuật viên X-quang'), ('ultrasound technician', 'Kỹ thuật viên siêu âm'), ('nurse', 'Y tá')], default='patient', max_length=100),
        ),
    ]
