# Generated by Django 3.2 on 2021-07-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210731_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='identifier',
            new_name='user_identifier',
        ),
    ]
