# Generated by Django 3.2 on 2021-09-27 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_myuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birthDate',
        ),
        migrations.AddField(
            model_name='myuser',
            name='birthdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
