# Generated by Django 3.2 on 2021-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_myuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nu')], default='', max_length=3),
        ),
    ]
