# Generated by Django 3.2 on 2021-07-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_identifier_myuser_user_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_identifier',
            new_name='identifier',
        ),
    ]
