# Generated by Django 3.2 on 2021-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211017_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='contact_relationship',
            field=models.CharField(blank=True, choices=[('C', 'Liên hệ khẩn cấp'), ('E', 'Chủ sở hữu lao động'), ('F', 'Cơ quan liên bang'), ('I', 'Công ty bảo hiểm'), ('N', 'Người nối dõi'), ('S', 'Cơ quan nhà nước'), ('U', 'Không xác định')], max_length=100, null=True),
        ),
    ]
