# Generated by Django 3.2 on 2021-07-19 08:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_id', models.IntegerField(unique=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.IntegerField(default=0)),
                ('respiratory_rate', models.IntegerField(default=0)),
                ('diastolic_blood_pressure', models.IntegerField(default=0)),
                ('systolic_blood_pressure', models.IntegerField(default=0)),
                ('body_temperature', models.IntegerField(default=0)),
                ('heart_rate', models.IntegerField(default=0)),
                ('encounter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fhir.encounter')),
            ],
        ),
    ]
