# Generated by Django 3.2 on 2021-09-12 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterModel',
            fields=[
                ('encounter_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('encounter_start', models.DateTimeField(default=datetime.datetime.now)),
                ('encounter_end', models.DateTimeField(null=True)),
                ('encounter_status', models.CharField(default='in-progress', max_length=20)),
                ('encounter_class', models.CharField(choices=[('IMP', 'Nội trú'), ('AMB', 'Ambulatory'), ('FLD', 'Khám tại địa điểm ngoài'), ('EMER', 'Khẩn cấp'), ('HH', 'Khám tại nhà'), ('ACUTE', 'Nội trú khẩn cấp'), ('NONAC', 'Nội trú không khẩn cấp'), ('OBSENC', 'Thăm khám quan sát'), ('SS', 'Ngoại trú'), ('VR', 'Trực tuyến'), ('PRENC', 'Tái khám')], default='AMB', max_length=10, null=True)),
                ('encounter_type', models.CharField(choices=[('Bệnh án nội khoa', 'Bệnh án nội khoa'), ('Bệnh án ngoại khoa', 'Bệnh án ngoại khoa'), ('Bệnh án phụ khoa', 'Bệnh án phụ khoa'), ('Bệnh án sản khoa', 'Bệnh án sản khoa')], default='2', max_length=30, null=True)),
                ('encounter_service', models.CharField(max_length=20, null=True)),
                ('encounter_priority', models.CharField(choices=[('A', 'ASAP'), ('EL', 'Tự chọn'), ('EM', 'Khẩn cấp'), ('P', 'Trước'), ('R', 'Bình thường'), ('S', 'Star')], max_length=10, null=True)),
                ('encounter_reason', models.CharField(max_length=10, null=True)),
                ('encounter_submitted', models.BooleanField(default=False)),
                ('user_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('birthDate', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='', max_length=3)),
                ('work_address', models.CharField(default='', max_length=255)),
                ('home_address', models.CharField(default='', max_length=255)),
                ('telecom', models.CharField(default='', max_length=10)),
                ('group_name', models.CharField(default='patient', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestModel',
            fields=[
                ('service_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_status', models.CharField(default='active', max_length=100)),
                ('service_category', models.CharField(max_length=10)),
                ('service_code', models.CharField(max_length=100, null=True)),
                ('service_requester', models.CharField(max_length=100, null=True)),
                ('service_note', models.CharField(max_length=100, null=True)),
                ('service_occurrence', models.DateField(max_length=100)),
                ('service_authored', models.DateField(max_length=100)),
                ('encounter_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureModel',
            fields=[
                ('procedure_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('procedure_status', models.CharField(max_length=100)),
                ('procedure_category', models.CharField(choices=[('22642003', 'Phương pháp hoặc dịch vụ tâm thần'), ('409063005', 'Tư vấn'), ('409073007', 'Giáo dục'), ('387713003', 'Phẫu thuật'), ('103693007', 'Chuẩn đoán'), ('46947000', 'Phương pháp chỉnh hình'), ('410606002', 'Phương pháp dịch vụ xã hội')], max_length=100)),
                ('procedure_code', models.CharField(max_length=100)),
                ('procedure_performedDateTime', models.DateTimeField(null=True)),
                ('procedure_asserter', models.CharField(max_length=100, null=True)),
                ('procedure_performer', models.CharField(max_length=100, null=True)),
                ('procedure_location', models.CharField(max_length=100, null=True)),
                ('procedure_reasonCode', models.CharField(max_length=100, null=True)),
                ('procedure_outcome', models.CharField(max_length=100, null=True)),
                ('procedure_complication', models.CharField(max_length=100, null=True)),
                ('procedure_followUp', models.CharField(max_length=100, null=True)),
                ('procedure_focalDevice', models.CharField(max_length=100, null=True)),
                ('procedure_note', models.CharField(max_length=100, null=True)),
                ('encounter_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationModel',
            fields=[
                ('service_identifier', models.CharField(default='', max_length=100)),
                ('observation_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('observation_status', models.CharField(default='registered', max_length=10)),
                ('observation_code', models.CharField(default='', max_length=100)),
                ('observation_category', models.CharField(default='', max_length=10)),
                ('observation_effective', models.DateTimeField(default=datetime.datetime.now)),
                ('observation_valuequantity', models.CharField(default='', max_length=10, null=True)),
                ('observation_valueunit', models.CharField(default='', max_length=10)),
                ('observation_performer', models.CharField(default='', max_length=100)),
                ('observation_note', models.CharField(default='', max_length=300, null=True)),
                ('encounter_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationModel',
            fields=[
                ('medication_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('medication_medication', models.CharField(max_length=100)),
                ('medication_reasonCode', models.CharField(max_length=100)),
                ('medication_effective', models.DateField()),
                ('medication_dateAsserted', models.DateField()),
                ('dosage_additional_instruction', models.CharField(max_length=100)),
                ('dosage_patient_instruction', models.CharField(max_length=100)),
                ('dosage_frequency', models.CharField(max_length=100)),
                ('dosage_period', models.CharField(max_length=100)),
                ('dosage_duration', models.CharField(max_length=100)),
                ('dosage_route', models.CharField(max_length=100)),
                ('dosage_quantity', models.CharField(max_length=100)),
                ('dosage_when', models.CharField(max_length=100)),
                ('dosage_offset', models.CharField(default=0, max_length=100)),
                ('encounter_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionModel',
            fields=[
                ('condition_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('condition_code', models.CharField(default='', max_length=100)),
                ('condition_clinicalstatus', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('recurrence', 'Recurrence'), ('relapse', 'Relapse'), ('remission', 'Remission'), ('resolved', 'Resolves')], max_length=100)),
                ('condition_onset', models.DateTimeField(default='')),
                ('condition_severity', models.CharField(choices=[('24484000', 'Nặng'), ('6736007', 'Vừa'), ('255604002', 'Nhẹ')], max_length=100)),
                ('encounter_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllergyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_clinical_status', models.CharField(max_length=100)),
                ('allergy_type', models.CharField(max_length=100)),
                ('allergy_category', models.CharField(max_length=100)),
                ('allergy_code', models.CharField(max_length=100)),
                ('allergy_criticality', models.CharField(max_length=100)),
                ('allergy_onset', models.DateField(null=True)),
                ('allergy_last_occurrence', models.DateField(null=True)),
                ('allergy_reaction', models.CharField(max_length=100, null=True)),
                ('patient_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
