# Generated by Django 3.2 on 2021-07-20 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_status', models.CharField(max_length=100)),
                ('allergy_type', models.CharField(max_length=100)),
                ('allergy_category', models.CharField(max_length=100)),
                ('allergy_code', models.CharField(max_length=100)),
                ('allergy_criticality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicalStatus', models.CharField(max_length=100)),
                ('onset', models.DateTimeField()),
                ('severity', models.CharField(max_length=100)),
                ('self_history', models.CharField(max_length=100)),
                ('allergy', models.CharField(max_length=100)),
                ('family_history', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('encounter_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('class_select', models.CharField(default='', max_length=10)),
                ('type_select', models.CharField(default='', max_length=30)),
                ('service_type', models.CharField(default='', max_length=20)),
                ('priority', models.CharField(default='', max_length=10)),
                ('reason_code', models.CharField(default='', max_length=10)),
                ('location', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='', max_length=3)),
                ('work_address', models.CharField(default='', max_length=255)),
                ('home_address', models.CharField(default='', max_length=255)),
                ('telecom', models.CharField(default='', max_length=10)),
                ('group_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicerequest_id', models.CharField(max_length=20)),
                ('request_status', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=10)),
                ('request_location', models.CharField(max_length=100)),
                ('request_note', models.TextField()),
                ('request_description', models.TextField()),
                ('encounter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_status', models.CharField(max_length=100)),
                ('procedure_category', models.CharField(max_length=100)),
                ('procedure_code', models.CharField(max_length=100)),
                ('procedure_location', models.CharField(max_length=100)),
                ('procedure_outcome', models.CharField(max_length=100)),
                ('encounter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=10)),
                ('category', models.CharField(default='', max_length=10)),
                ('effective', models.DateTimeField(default=datetime.datetime.now)),
                ('valuequantity', models.CharField(default='', max_length=10)),
                ('valueunit', models.CharField(default='', max_length=10)),
                ('performer', models.CharField(default='', max_length=100)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('effective', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('encounter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encounter')),
            ],
        ),
    ]
