# Generated by Django 3.2 on 2021-07-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='service_identifier',
            field=models.CharField(default='', max_length=100),
        ),
    ]
