# Generated by Django 3.2 on 2021-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountermodel',
            name='encounter_length',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
