# Generated by Django 3.2 on 2021-09-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0002_auto_20210929_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionmodel',
            old_name='condition_clinicalstatus',
            new_name='condition_clinical_status',
        ),
    ]
