# Generated by Django 3.2 on 2021-07-21 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fhir', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterModel',
            fields=[
                ('encounter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('class_select', models.CharField(default='', max_length=10)),
                ('type_select', models.CharField(default='', max_length=30)),
                ('service_type', models.CharField(default='', max_length=20)),
                ('priority', models.CharField(default='', max_length=10)),
                ('reason_code', models.CharField(default='', max_length=10)),
                ('location', models.CharField(default='', max_length=20)),
                ('user_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Allergy',
            new_name='AllergyModel',
        ),
        migrations.RenameModel(
            old_name='Observation',
            new_name='ObservationModel',
        ),
        migrations.RenameModel(
            old_name='Condition',
            new_name='ConditionModel',
        ),
        migrations.RenameModel(
            old_name='Medicine',
            new_name='MedicineModel',
        ),
        migrations.RenameModel(
            old_name='Procedure',
            new_name='ProcedureModel',
        ),
        migrations.RenameModel(
            old_name='ServiceRequest',
            new_name='ServiceRequestModel',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel'),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel'),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel'),
        ),
    ]
