# Generated by Django 3.2 on 2021-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0002_auto_20210906_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceduremodel',
            old_name='procedure_bodySite',
            new_name='procedure_reasonCode',
        ),
        migrations.AddField(
            model_name='proceduremodel',
            name='procedure_performedDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='procedure_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='procedure_outcome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
