# Generated by Django 3.2 on 2021-09-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0002_encountermodel_encounter_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='service_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.servicerequestmodel'),
        ),
    ]
