# Generated by Django 3.2 on 2021-07-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0002_alter_conditionmodel_encounter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionmodel',
            old_name='condition_id',
            new_name='condition_identifier',
        ),
        migrations.RenameField(
            model_name='conditionmodel',
            old_name='encounter_id',
            new_name='encounter_identifier',
        ),
        migrations.RenameField(
            model_name='encountermodel',
            old_name='encounter_id',
            new_name='encounter_identifier',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='encounter_id',
            new_name='encounter_identifier',
        ),
        migrations.RenameField(
            model_name='observationmodel',
            old_name='observation_id',
            new_name='observation_identifier',
        ),
        migrations.RenameField(
            model_name='observationmodel',
            old_name='service_id',
            new_name='service_identifier',
        ),
        migrations.RenameField(
            model_name='proceduremodel',
            old_name='encounter_id',
            new_name='encounter_identifier',
        ),
        migrations.RenameField(
            model_name='servicerequestmodel',
            old_name='encounter_id',
            new_name='encounter_identifier',
        ),
        migrations.RenameField(
            model_name='servicerequestmodel',
            old_name='service_id',
            new_name='service_identifier',
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_onset',
            field=models.DateTimeField(default=''),
        ),
    ]
