# Generated by Django 3.2 on 2021-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0002_auto_20210805_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encountermodel',
            name='encounter_location',
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_severity',
            field=models.CharField(choices=[('24484000', 'Nặng'), ('6736007', 'Vừa'), ('255604002', 'Nhẹ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_class',
            field=models.CharField(choices=[('IMP', 'Nội trú'), ('AMB', 'Ambulatory'), ('FLD', 'Khám tại địa điểm ngoài'), ('EMER', 'Khẩn cấp'), ('HH', 'Khám tại nhà'), ('ACUTE', 'Nội trú khẩn cấp'), ('NONAC', 'Nội trú không khẩn cấp'), ('OBSENC', 'Thăm khám quan sát'), ('SS', 'Ngoại trú'), ('VR', 'Trực tuyến'), ('PRENC', 'Tái khám')], default='AMB', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_priority',
            field=models.CharField(choices=[('A', 'ASAP'), ('EL', 'Tự chọn'), ('EM', 'Khẩn cấp'), ('P', 'Trước'), ('R', 'Bình thường'), ('S', 'Star')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_reason',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_service',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_type',
            field=models.CharField(choices=[('Bệnh án nội khoa', 'Bệnh án nội khoa'), ('Bệnh án ngoại khoa', 'Bệnh án ngoại khoa'), ('Bệnh án phụ khoa', 'Bệnh án phụ khoa'), ('Bệnh án sản khoa', 'Bệnh án sản khoa')], default='2', max_length=30, null=True),
        ),
    ]
