# Generated by Django 3.2 on 2021-07-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0002_alter_observationmodel_service_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequestmodel',
            old_name='service_description',
            new_name='service_code',
        ),
    ]
