# Generated by Django 3.2 on 2021-09-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_rename_condition_clinicalstatus_conditionmodel_condition_clinical_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionmodel',
            name='condition_use',
        ),
        migrations.AddField(
            model_name='conditionmodel',
            name='condition_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
