# Generated by Django 3.2 on 2021-09-27 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_alter_observationmodel_service_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationmodel',
            name='medication_reasonCode',
        ),
        migrations.RemoveField(
            model_name='observationmodel',
            name='observation_valuequantity',
        ),
        migrations.RemoveField(
            model_name='observationmodel',
            name='observation_valueunit',
        ),
        migrations.RemoveField(
            model_name='proceduremodel',
            name='procedure_followUp',
        ),
        migrations.RemoveField(
            model_name='proceduremodel',
            name='procedure_reasonCode',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='birthDate',
        ),
        migrations.AddField(
            model_name='medicationmodel',
            name='medication_reason_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='observationmodel',
            name='observation_value_quantity',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='observationmodel',
            name='observation_value_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='proceduremodel',
            name='procedure_follow_up',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceduremodel',
            name='procedure_reason_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birthdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
