# Generated by Django 3.2 on 2021-08-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_auto_20210805_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_type',
            field=models.CharField(choices=[('Bệnh án nội khoa', 'Bệnh án nội khoa'), ('Bệnh án ngoại khoa', 'Bệnh án ngoại khoa'), ('Bệnh án phụ khoa', 'Bệnh án phụ khoa'), ('Bệnh án sản khoa', 'Bệnh án sản khoa')], default='Bệnh án ngoại khoa', max_length=100, null=True),
        ),
    ]
