# Generated by Django 3.2 on 2021-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_schedulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='session',
            field=models.CharField(default='morning', max_length=20),
            preserve_default=False,
        ),
    ]
