# Generated by Django 3.2 on 2021-12-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_auto_20211216_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='practitioner_department',
        ),
    ]
