# Generated by Django 3.2 on 2021-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_rename_service_description_servicerequestmodel_service_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_identifier',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='group_name',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
