# Generated by Django 3.2 on 2021-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_auto_20210721_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountermodel',
            name='encounter_status',
            field=models.CharField(default='in-progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='class_select',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='priority',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='reason_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='service_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='type_select',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
