# Generated by Django 3.2 on 2021-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0004_auto_20210927_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationmodel',
            name='medication_dateAsserted',
        ),
        migrations.AddField(
            model_name='medicationmodel',
            name='medication_date_asserted',
            field=models.DateField(null=True),
        ),
    ]
