# Generated by Django 3.2 on 2021-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0004_alter_encountermodel_encounter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
