# Generated by Django 3.2 on 2021-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0004_remove_schedule_practitioner_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_class',
            field=models.CharField(choices=[('SS', 'Thăm khám trong ngày'), ('IMP', 'Nội trú'), ('AMB', 'Ngoại trú'), ('FLD', 'Khám tại địa điểm ngoài'), ('EMER', 'Phòng cấp cứu'), ('HH', 'Khám tại nhà'), ('ACUTE', 'Nội trú khẩn cấp'), ('NONAC', 'Nội trú không khẩn cấp'), ('OBSENC', 'Thăm khám quan sát'), ('VR', 'Trực tuyến'), ('PRENC', 'Tái khám')], default='SS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_priority',
            field=models.CharField(choices=[('R', 'Bình thường'), ('EL', 'Tùy chọn'), ('A', 'Sớm nhất có thể'), ('UR', 'Cấp bách'), ('EM', 'Khẩn cấp'), ('S', 'Khẩn cấp nhất'), ('P', 'Kiểm tra trước phẫu thuật')], max_length=10, null=True),
        ),
    ]
