# Generated by Django 3.2 on 2021-09-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0004_auto_20210906_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceduremodel',
            old_name='procecure_identifier',
            new_name='procedure_identifier',
        ),
    ]
