# Generated by Django 3.2 on 2021-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0004_auto_20210930_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationmodel',
            name='medication_status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequestmodel',
            name='service_intent',
            field=models.CharField(default='order', max_length=100),
        ),
    ]
