# Generated by Django 3.2 on 2021-07-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0004_auto_20210731_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_clinicalstatus',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('recurrence', 'Recurrence'), ('relapse', 'Relapse'), ('remission', 'Remission'), ('resolved', 'Resolves')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='service_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
