# Generated by Django 3.2 on 2021-11-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0005_alter_encountermodel_encounter_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encountermodel',
            old_name='user_identifier',
            new_name='patient',
        ),
    ]
