# Generated by Django 3.2 on 2021-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0005_auto_20210927_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduremodel',
            name='procedure_performedDateTime',
        ),
        migrations.AddField(
            model_name='proceduremodel',
            name='procedure_performed_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
