# Generated by Django 3.2 on 2021-07-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0005_auto_20210721_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
