# Generated by Django 3.2 on 2021-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0006_encountermodel_encounter_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionmodel',
            name='condition_verification_status',
            field=models.CharField(default='confirmed', max_length=100),
        ),
    ]
