# Generated by Django 3.2 on 2021-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0006_alter_encountermodel_encounter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_status',
            field=models.CharField(default='in-progress', max_length=20),
        ),
    ]
