# Generated by Django 3.2 on 2021-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0006_rename_user_identifier_encountermodel_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_name', models.CharField(max_length=100)),
                ('practitioner_identifier', models.CharField(max_length=20)),
                ('practitioner_location', models.CharField(max_length=100, null=True)),
                ('planned_encounter', models.CharField(max_length=100)),
                ('encounter_date', models.DateField()),
                ('session', models.CharField(max_length=20)),
            ],
        ),
    ]
