# Generated by Django 3.2 on 2021-10-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0007_conditionmodel_condition_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encountermodel',
            name='encounter_submitted',
        ),
    ]
