# Generated by Django 3.2 on 2021-07-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0007_alter_encountermodel_encounter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='class_select',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='priority',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='reason_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='service_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='type_select',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
