# Generated by Django 3.2 on 2021-11-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0007_assignedencounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedencounter',
            name='planned_encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fhir.encountermodel'),
        ),
    ]
