# Generated by Django 3.2 on 2021-12-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0007_encountermodel_encounter_sharing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequestmodel',
            old_name='serivce_requester_identifier',
            new_name='service_requester_identifier',
        ),
    ]
