# Generated by Django 3.2 on 2021-11-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0008_alter_assignedencounter_planned_encounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedencounter',
            old_name='planned_encounter',
            new_name='assigned_encounter',
        ),
    ]
