# Generated by Django 3.2 on 2021-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0008_auto_20210721_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountermodel',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='class_select',
            field=models.CharField(choices=[('IMP', 'Nội trú'), ('AMB', 'Ambulatory'), ('FLD', 'Khám tại địa điểm ngoài'), ('EMER', 'Khẩn cấp'), ('HH', 'Khám tại nhà'), ('ACUTE', 'Nội trú khẩn cấp'), ('NONAC', 'Nội trú không khẩn cấp'), ('OBSENC', 'Thăm khám quan sát'), ('SS', 'Ngoại trú'), ('VR', 'Trực tuyến'), ('PRENC', 'Tái khám')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='location',
            field=models.CharField(choices=[('1', 'Khoa Khám bệnh'), ('2', 'Khoa Hồi sức cấp cứu'), ('3', 'Khoa Nội tổng hợp'), ('4', 'Khoa Nội tổng hợp'), ('5', 'Khoa Nội tiêu hóa'), ('6', 'Khoa Nội - tiết niệu'), ('7', 'Khoa Nội tiết'), ('8', 'Khoa Nội cơ - xương - khớp'), ('9', 'Khoa Nội tiết'), ('10', 'Khoa Dị ứng'), ('11', 'Khoa Huyết học lâm sàng'), ('12', 'Khoa Truyền nhiễm'), ('13', 'Khoa Lao'), ('14', 'Khoa Tâm thần'), ('15', 'Khoa Thần kinh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='priority',
            field=models.CharField(choices=[('A', 'ASAP'), ('EL', 'Tự chọn'), ('EM', 'Khẩn cấp'), ('P', 'Trước'), ('R', 'Bình thường'), ('S', 'Star')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='type_select',
            field=models.CharField(choices=[('1', 'Bệnh án nội khoa'), ('2', 'Bệnh án ngoại khoa'), ('3', 'Bệnh án phụ khoa'), ('4', 'Bệnh án sản khoa')], max_length=30, null=True),
        ),
    ]
