# Generated by Django 3.2 on 2021-07-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0009_auto_20210722_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequestmodel',
            old_name='request_type',
            new_name='request_category',
        ),
        migrations.RemoveField(
            model_name='servicerequestmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='request_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='request_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='request_status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='servicerequest_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
