# Generated by Django 3.2 on 2021-10-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0009_auto_20211002_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreportmodel',
            name='diagnostic_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='medication_version',
            field=models.IntegerField(default=0),
        ),
    ]
