# Generated by Django 3.2 on 2021-12-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_practitionermodel_practitioner_role'),
        ('fhir', '0009_auto_20211218_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodel',
            name='service_requester',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestmodel',
            name='service_requester_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requester', to='administration.practitionermodel'),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='service_performer_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_performer', to='administration.practitionermodel'),
        ),
    ]
