# Generated by Django 3.2 on 2021-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0010_auto_20210722_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionmodel',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='clinicalStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Recurrence', 'Recurrence'), ('Relapse', 'Relapse'), ('Remission', 'Remission'), ('Resolved', 'Resolves')], max_length=100),
        ),
    ]
