# Generated by Django 3.2 on 2021-12-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0010_auto_20211204_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComorbidityDiseases',
            new_name='ComorbidityDisease',
        ),
        migrations.RenameModel(
            old_name='DischargeDiseases',
            new_name='DischargeDisease',
        ),
        migrations.RenameModel(
            old_name='ScheduleModel',
            new_name='Schedule',
        ),
    ]
