# Generated by Django 3.2 on 2021-12-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0010_auto_20211218_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodel',
            name='service_reason_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
