# Generated by Django 3.2 on 2021-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0011_auto_20211003_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_duration_unit',
            field=models.CharField(choices=[('s', 'giây'), ('min', 'phút'), ('h', 'giờ'), ('d', 'ngày'), ('wk', 'tuần'), ('mo', 'tháng'), ('a', 'năm')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_frequency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_offset',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_period_unit',
            field=models.CharField(choices=[('s', 'giây'), ('min', 'phút'), ('h', 'giờ'), ('d', 'ngày'), ('wk', 'tuần'), ('mo', 'tháng'), ('a', 'năm')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_quantity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_route',
            field=models.CharField(max_length=10),
        ),
    ]
