# Generated by Django 3.2 on 2021-07-22 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0011_auto_20210722_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionmodel',
            name='onset',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
