# Generated by Django 3.2 on 2021-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0012_alter_conditionmodel_onset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionmodel',
            name='severity',
            field=models.CharField(choices=[('24484000', 'Nặng'), ('6736007', 'Vừa'), ('255604002', 'Nhẹ')], max_length=100),
        ),
    ]
