# Generated by Django 3.2 on 2021-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0012_auto_20211004_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_offset',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
