# Generated by Django 3.2 on 2021-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0013_alter_conditionmodel_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='observationmodel',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='status',
            field=models.CharField(default='registered', max_length=10),
        ),
    ]
