# Generated by Django 3.2 on 2021-10-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0013_alter_medicationmodel_dosage_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_route',
            field=models.CharField(max_length=100),
        ),
    ]
