# Generated by Django 3.2 on 2021-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0014_alter_medicationmodel_dosage_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_abatement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_onset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
