# Generated by Django 3.2 on 2021-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0014_auto_20210723_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='note',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='valuequantity',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
