# Generated by Django 3.2 on 2021-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0015_auto_20211004_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_clinical_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('recurrence', 'Recurrence'), ('relapse', 'Relapse'), ('remission', 'Remission'), ('resolved', 'Resolves')], max_length=100),
        ),
    ]
