# Generated by Django 3.2 on 2021-10-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0018_allergymodel_allergy_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergymodel',
            name='allergy_version',
            field=models.IntegerField(default=0),
        ),
    ]
