# Generated by Django 3.2 on 2021-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0019_allergymodel_allergy_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_class',
            field=models.CharField(choices=[('IMP', 'Nội trú'), ('AMB', 'Ngoại trú'), ('FLD', 'Khám tại địa điểm ngoài'), ('EMER', 'Khẩn cấp'), ('HH', 'Khám tại nhà'), ('ACUTE', 'Nội trú khẩn cấp'), ('NONAC', 'Nội trú không khẩn cấp'), ('OBSENC', 'Thăm khám quan sát'), ('SS', 'Thăm khám trong ngày'), ('VR', 'Trực tuyến'), ('PRENC', 'Tái khám')], default='AMB', max_length=10, null=True),
        ),
    ]
