# Generated by Django 3.2 on 2021-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0020_alter_encountermodel_encounter_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='contact_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='contact_gender',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='contact_telecom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
