# Generated by Django 3.2 on 2021-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0023_alter_usermodel_contact_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_additional_instruction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='dosage_patient_instruction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
