# Generated by Django 3.2 on 2022-01-13 03:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0023_auto_20220113_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergymodel',
            name='allergy_recorded_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 3, 40, 24, 428969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='encountermodel',
            name='encounter_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 3, 40, 24, 424980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='observation_effective',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 3, 40, 24, 426975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 3, 40, 24, 277332, tzinfo=utc)),
        ),
    ]
