# Generated by Django 3.2 on 2021-11-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0024_auto_20211107_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=10)),
                ('disease_name', models.CharField(max_length=100, unique=True)),
                ('disease_search', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComorbidityDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=10)),
                ('disease_name', models.CharField(max_length=100, unique=True)),
                ('disease_search', models.CharField(max_length=100)),
                ('discharge_diseases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir.dischargediseases')),
            ],
        ),
    ]
