# Generated by Django 3.2 on 2021-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0025_comorbiditydiseases_dischargediseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbiditydiseases',
            name='disease_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargediseases',
            name='disease_name',
            field=models.CharField(max_length=100),
        ),
    ]
